algoritmo "semnome"
//informar salario e retornar com um aumento de 30%
var
salario, aumento: real

inicio
escreval("______________________________________________________________________")
escreval("Informe o seu salario: ")
leia(salario)
escreval("______________________________________________________________________")
aumento <- salario * 0.3 + salario

Escreval("seu salario reajustado é de:", aumento, " R$")
escreval("______________________________________________________________________")
fimalgoritmo
